### ISSUE TITLE
Internal Server Error: /fieldsight/sendmultiusermultilevelinvite/

### ISSUE THREAD

**Issue by raeesaroj** [fieldsight/fieldsight#206]
Traceback (most recent call last):   File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response     response = wrapped_callback(request, *callback_args, **callback_kwargs)   File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view     return view_func(request, *args, **kwargs)   File "./onadata/apps/fieldsight/views.py", line 1714, in sendmultiroleuserinvite     'user': User.objects.get(email=invite.email),   File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method     return getattr(self.get_queryset(), name)(*args, **kwargs)   File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get     self.model._meta.object_name DoesNotExist: User matching query does not exist.

**Comment by raeesaroj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Internal Server Error: /fieldsight/sendmultiusermultilevelinvite/](https://trello.com/c/HPXJX1dZ/616-internal-server-error-fieldsight-sendmultiusermultilevelinvite)
