### ISSUE TITLE
api error on /forms/api/instance-list/

### ISSUE THREAD

**Issue by awemulya** [fieldsight/fieldsight#217]
invite.fieldsight@gmail.com
9:45 AM (17 minutes ago)
to me, mearunbhandari, raesaroj16, skhatri.np

Internal Server Error: /forms/api/instance-list/
Traceback (most recent call last):
  File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 45, in list
    return self.get_paginated_response(serializer.data)
  File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 674, in data
    ret = super(ListSerializer, self).data
  File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 239, in data
    self._data = self.to_representation(self.instance)
  File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 614, in to_representation
    self.child.to_representation(item) for item in iterable
  File "./onadata/libs/serializers/data_serializer.py", line 91, in to_representation
    return MongoHelper.to_readable_dict(returned_dict)
  File "./onadata/apps/api/mongo_helper.py", line 32, in to_readable_dict
    for key, value in list(d.items()):
AttributeError: 'list' object has no attribute 'items'

**Comment by awemulya** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [api error on /forms/api/instance-list/](https://trello.com/c/dWxOo3HZ/645-api-error-on-forms-api-instance-list)
