### ISSUE TITLE
Full Map in Project Dashboard sends out error email about Geo-JSON.

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight#219]
Snippet of email below:
 
Internal Server Error: /fieldsight/api/project/322/sites/geoJSON/
Traceback (most recent call last):
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
   return view_func(request, *args, **kwargs)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
   return self.dispatch(request, *args, **kwargs)
 File "./onadata/apps/fieldsight/rolemixins.py", line 640, in dispatch
   return super(FullMapViewMixin, self).dispatch(request, *args, **kwargs)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
   return handler(request, *args, **kwargs)
 File "./onadata/apps/fieldsight/views.py", line 4243, in get
   fields=('name', 'location', 'id', 'identifier' ))
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/django/core/serializers/__init__.py", line 128, in serialize
   s = get_serializer(format)()
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/django/core/serializers/__init__.py", line 99, in get_serializer
   raise SerializerDoesNotExist(format)
SerializerDoesNotExist: u'full_detail_geojson'

**Comment by santoshkhatrii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Full Map in Project Dashboard sends out error email about Geo-JSON.](https://trello.com/c/0UPOmDAP/648-full-map-in-project-dashboard-sends-out-error-email-about-geo-json)
