### ISSUE TITLE
[Live Server] Error while deploying substages in staged forms

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight#222]
/forms/api/set-deploy-main-stage/1/191/965808/ 

Error occured while deploying sybstages.

Excerpt from email received:

Internal Server Error: /forms/api/set-deploy-main-stage/1/280/1093719/
Traceback (most recent call last):
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
   return view_func(*args, **kwargs)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
   return self.dispatch(request, *args, **kwargs)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
   response = self.handle_exception(exc)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
   response = handler(request, *args, **kwargs)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/rest_framework/decorators.py", line 53, in handler
   return func(*args, **kwargs)
 File "./onadata/apps/fsforms/views.py", line 2111, in set_deploy_main_stage
   copy_stage_to_sites.apply_async((), {'main_stage': main_stage, 'pk': pk}, countdown=2)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/celery/app/task.py", line 535, in apply_async
   **options
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/celery/app/base.py", line 745, in send_task
   amqp.send_task_message(P, name, message, **options)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/celery/app/amqp.py", line 552, in send_task_message
   **properties
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/kombu/messaging.py", line 169, in publish
   compression, headers)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/kombu/messaging.py", line 252, in _prepare
   body) = dumps(body, serializer=serializer)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/kombu/serialization.py", line 221, in dumps
   payload = encoder(data)
 File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
   self.gen.throw(type, value, traceback)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
   reraise(wrapper, wrapper(exc), sys.exc_info()[2])
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
   yield
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/kombu/serialization.py", line 221, in dumps
   payload = encoder(data)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/kombu/utils/json.py", line 69, in dumps
   **dict(default_kwargs, **kwargs))
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/simplejson/__init__.py", line 334, in dumps
   **kw).encode(obj)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/simplejson/encoder.py", line 237, in encode
   chunks = self.iterencode(o, _one_shot=True)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/simplejson/encoder.py", line 311, in iterencode
   return _iterencode(o, 0)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/kombu/utils/json.py", line 59, in default
   return super(JSONEncoder, self).default(o)
 File "/srv/fieldsight/kobocat/local/lib/python2.7/site-packages/simplejson/encoder.py", line 213, in default
   raise TypeError(repr(o) + " is not JSON serializable")
EncodeError: <Stage: A> is not JSON serializable

**Comment by santoshkhatrii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Live Server] Error while deploying substages in staged forms](https://trello.com/c/IjRQFQkx/652-live-server-error-while-deploying-substages-in-staged-forms)
